version: '3'

services:
  app:
    image: tomcat:9-jdk8-openjdk
    env_file:
      - .env
    ports:
      - '80:8080'
    volumes:
      - ./target/sampleImplement.war:/usr/local/tomcat/webapps/ROOT.war
