version: '3'

services:
  app:
    image: tomcat:9-jdk8-openjdk
    env_file:
      - .env
    ports:
      - '80:8080'
    volumes:
      - ./target/sampleImplement.war:/usr/local/tomcat/webapps/ROOT.war
  
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
